/* Auto-generated wrapper header for bindgen */
/* Generated by header_wrapper_generator.py */

/* Headers from lib/packagekit-glib2 */
#include <packagekit-glib2/packagekit.h>
#include <packagekit-glib2/pk-bitfield.h>
#include <packagekit-glib2/pk-category.h>
#include <packagekit-glib2/pk-client-helper.h>
#include <packagekit-glib2/pk-client-sync.h>
#include <packagekit-glib2/pk-client.h>
#include <packagekit-glib2/pk-common.h>
#include <packagekit-glib2/pk-console-shared.h>
#include <packagekit-glib2/pk-control-sync.h>
#include <packagekit-glib2/pk-control.h>
#include <packagekit-glib2/pk-debug.h>
#include <packagekit-glib2/pk-desktop.h>
#include <packagekit-glib2/pk-distro-upgrade.h>
#include <packagekit-glib2/pk-enum.h>
#include <packagekit-glib2/pk-error.h>
#include <packagekit-glib2/pk-eula-required.h>
#include <packagekit-glib2/pk-files.h>
#include <packagekit-glib2/pk-item-progress.h>
#include <packagekit-glib2/pk-media-change-required.h>
#include <packagekit-glib2/pk-offline.h>
#include <packagekit-glib2/pk-package-id.h>
#include <packagekit-glib2/pk-package-ids.h>
#include <packagekit-glib2/pk-package-sack-sync.h>
#include <packagekit-glib2/pk-package-sack.h>
#include <packagekit-glib2/pk-package.h>
#include <packagekit-glib2/pk-progress-bar.h>
#include <packagekit-glib2/pk-progress.h>
#include <packagekit-glib2/pk-repo-signature-required.h>
#include <packagekit-glib2/pk-require-restart.h>
#include <packagekit-glib2/pk-results.h>
#include <packagekit-glib2/pk-source.h>
#include <packagekit-glib2/pk-spawn-polkit-agent.h>
#include <packagekit-glib2/pk-task-sync.h>
#include <packagekit-glib2/pk-task-text.h>
#include <packagekit-glib2/pk-task-wrapper.h>
#include <packagekit-glib2/pk-task.h>
#include <packagekit-glib2/pk-transaction-list.h>
#include <packagekit-glib2/pk-transaction-past.h>

/* Headers from src */
//#include "src/packagekit-plugin.h"
#include "src/pk-backend-job.h"
#include "src/pk-backend-spawn.h"
#include "src/pk-backend.h"
#include "src/pk-dbus.h"
#include "src/pk-engine.h"
#include "src/pk-scheduler.h"
#include "src/pk-shared.h"
#include "src/pk-spawn.h"
#include "src/pk-transaction-db.h"
#include "src/pk-transaction.h"
